# Generated by Django 4.2.3 on 2023-08-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
