# Generated by Django 4.2.3 on 2023-08-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='')),
                ('company', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
